name: Build App bundleRelease

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: ${{ secrets.MYAPP_UPLOAD_IMC_STORE_FILE }}
          encodedString: ${{ secrets.KEYSTORE_IMC_ENCODING }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Build prod
        run: |
          cd mobile 
          yarn 
          cd android
          ./gradlew bundleRelease -PMYAPP_UPLOAD_IMC_STORE_FILE="${{ steps.decode_keystore.outputs.filePath }}" \
                                  -PMYAPP_UPLOAD_IMC_KEY_ALIAS="${{ secrets.MYAPP_UPLOAD_IMC_KEY_ALIAS }}" \
                                  -PMYAPP_UPLOAD_IMC_STORE_PASSWORD="${{ secrets.MYAPP_UPLOAD_IMC_STORE_PASSWORD }}" \
                                  -PMYAPP_UPLOAD_IMC_KEY_PASSWORD="${{ secrets.MYAPP_UPLOAD_IMC_KEY_PASSWORD }}" \
                                  -PMYAPP_IMC_VERSION_CODE="${{github.run_number}}" \
                                  -PMYAPP_IMC_VERSION_NAME="${{ github.ref_name }}"
        env:
          CI: true

      - name: Upload to PlayStore
        uses: r0adkll/upload-google-play@v1
        with:
        serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
        packageName: com.app.imccalc
        releaseFiles: mobile/android/app/build/outputs/bundle/release/app-release.aab
        track: internal
        status: completed
