name: Build Release App Bundle

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: ${{ secrets.MYAPP_UPLOAD_IMC_STORE_FILE }}
          encodedString: ${{ secrets.KEYSTORE_IMC_ENCODING }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Configurar variáveis Gradle
        run: |
          echo "MYAPP_UPLOAD_IMC_STORE_FILE=${{ steps.decode_keystore.outputs.filePath }}/${{ secrets.MYAPP_UPLOAD_IMC_STORE_FILE }}" >> $HOME/.gradle/gradle.properties
          echo "MYAPP_UPLOAD_IMC_KEY_ALIAS=${{ secrets.MYAPP_UPLOAD_IMC_KEY_ALIAS }}" >> $HOME/.gradle/gradle.properties
          echo "MYAPP_UPLOAD_IMC_STORE_PASSWORD=${{ secrets.MYAPP_UPLOAD_IMC_STORE_PASSWORD }}" >> $HOME/.gradle/gradle.properties
          echo "MYAPP_UPLOAD_IMC_KEY_PASSWORD=${{ secrets.MYAPP_UPLOAD_IMC_KEY_PASSWORD }}" >> $HOME/.gradle/gradle.properties

      - name: build prod
        run: cd mobile && yarn && cd android && ./gradlew assembleRelease
        env:
          CI: true

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Build Artifacts
          path: app/build/outputs/
