name: Build Release App Bundle

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: ${{ secrets.MYAPP_UPLOAD_IMC_STORE_FILE }}
          encodedString: ${{ secrets.KEYSTORE_IMC_ENCODING }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: build prod
        run: ./gradlew assembleRelease
        env:
          CI: true
          MYAPP_UPLOAD_IMC_STORE_FILE: ${{ steps.decode_keystore.outputs.filePath }}/${{ secrets.MYAPP_UPLOAD_IMC_STORE_FILE }}
          MYAPP_UPLOAD_IMC_KEY_ALIAS: ${{ secrets.MYAPP_UPLOAD_IMC_KEY_ALIAS }}
          MYAPP_UPLOAD_IMC_STORE_PASSWORD: ${{ secrets.MYAPP_UPLOAD_IMC_STORE_PASSWORD }}
          MYAPP_UPLOAD_IMC_KEY_PASSWORD: ${{ secrets.MYAPP_UPLOAD_IMC_KEY_PASSWORD }}

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Build Artifacts
          path: app/build/outputs/
